module TreRegex
  VERSION: String

  class Error < StandardError
  end

  type fuzzy_options = {
    ?max_errors: Integer,
    ?max_insertions: Integer,
    ?max_deletions: Integer,
    ?max_substitutions: Integer,
    ?max_cost: Integer,
    ?weight_insertion: Integer,
    ?weight_deletion: Integer,
    ?weight_substitution: Integer
  }

  type match_result = {
    match: String,
    submatches: Array[String?],
    index: Integer,
    end_index: Integer,
    cost: Integer,
    errors: {
      insertions: Integer,
      deletions: Integer,
      substitutions: Integer
    }
  }

  class Regex
    attr_reader pattern: String

    def initialize: (String pattern, ?ignore_case: bool) -> void
    def exec: (String text, ?fuzzy_options options) -> match_result?
    def test?: (String text, ?fuzzy_options options) -> bool
    def match_all: (String text, ?fuzzy_options options) ?{ (match_result) -> void } -> Enumerator[match_result, void]
    def self.finalize: (FFI::Pointer preg_ptr) -> ^() -> void
  end
end
